#!/usr/bin/env node
/**
 * Builds the self-hosted IBM Plex files (ADR 0005):
 *   - subsets Plex Sans 400 and 600 into a "core" range (ASCII, Latin-1, common punctuation) and an
 *     "ext" range (the rest of the fontsource latin subset) with pyftsubset;
 *   - subsets Plex Mono 400 to the core range (SKUs, prices, order numbers);
 *   - writes the Sans 600 core @font-face into apps/web/app/font-critical.css (every heading, incl. the
 *     LCP element; the file is preloaded from the root layout rather than inlined, which keeps the
 *     render-blocking stylesheet small — see ADR 0005).
 * Requires python3 with fonttools + brotli (`pip install fonttools brotli`). Commit the output.
 */
import { mkdirSync, statSync, writeFileSync, rmSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const web = resolve(root, "apps/web");
const src = (pkg, file) => resolve(web, "node_modules/@fontsource", pkg, "files", file);
const out = resolve(web, "public/fonts");
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

export const CORE = "U+0020-007E, U+00A0-00FF, U+2013-2014, U+2018-201A, U+201C-201E, U+2026, U+20AC, U+2122, U+2212, U+2215";
export const EXT = "U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-2012, U+2015-2017, U+201B, U+201F-2025, U+2027-206F, U+2191, U+2193, U+FEFF, U+FFFD";

function subset(input, output, unicodes) {
  execFileSync("pyftsubset", [input, `--output-file=${output}`, `--unicodes=${unicodes}`, "--flavor=woff2", "--layout-features=*", "--no-hinting", "--desubroutinize"], { stdio: "inherit" });
}

const sans = (w) => src("ibm-plex-sans", `ibm-plex-sans-latin-${w}-normal.woff2`);
subset(sans(400), resolve(out, "plex-sans-400-core.woff2"), CORE);
subset(sans(400), resolve(out, "plex-sans-400-ext.woff2"), EXT);
subset(sans(600), resolve(out, "plex-sans-600-ext.woff2"), EXT);
const core600 = resolve(out, "plex-sans-600-core.woff2");
subset(sans(600), core600, CORE);
subset(src("ibm-plex-mono", "ibm-plex-mono-latin-400-normal.woff2"), resolve(out, "plex-mono-400.woff2"), CORE);

const css = `/* GENERATED by scripts/sync-fonts.mjs — do not edit by hand. See ADR 0005. */
/* Plex Sans 600, core Latin: every heading (including the LCP element). Preloaded from the root layout;
   font-display: optional means the first paint is either Plex or the metric-matched fallback, never a
   swap after the fact (no CLS, no late LCP re-report). */
@font-face {
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 600;
  font-display: optional;
  src: url("/fonts/plex-sans-600-core.woff2") format("woff2");
  unicode-range: ${CORE};
}
`;
writeFileSync(resolve(web, "app/font-critical.css"), css);
console.log(`sync-fonts: wrote public/fonts (600 core ${Math.round(statSync(core600).size / 1024)} KB) and font-critical.css`);
